### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by josem32** [acalvoa/sails-hook-multitenant#8]
is this ready for production? I'm beginning a new project and want to use it.

Also I have another 2 questions:
1.- can it be used with PostgreSQL and schemas? for use schemas instead of multiples DB for each tenant.

2.- what happens when running in alter? does it migrate the changes on all the DB's?

thanks.

**Comment by acalvoa** [comment]
Hi, @josem32 sorry if i don't answered before. 

- Yes, It's ready for production stages. At present, we used this hook for three productions apps made by my team. So, you can use this hook in production stage with no problems. If you detect any problem with them, please notify us, and quickly will fix this. It's very important for my team, the optimal functionality of this hook.

- You can use with postgres, because we use Waterline to make posible the multitenancy. If your waterline have the postgres drivers, you can use this hook to make posible the multitenancy. This hook allows use multiple databases by tenant. It's only depende of your code logic to select the database used by tenant.

- At present, the migrate option its not suported, because normaly the origin of tenants is dinamic. But, its posible implement an aproximation of this. Maybe in the next release, we can work in this feature with my team.

Thanks to want use this hook.

**Comment by josem32** [comment]
Hi @acalvoa, thanks for the reply, we are using it already with MySQL and seems pretty fine so far.

any issue i'll make you know, thanks!
