### ISSUE TITLE
 the xxx.archive(req, xxx) method don't  work  

### ISSUE THREAD

**Issue by xhb** [acalvoa/sails-hook-multitenant#9]
version: 
  sails 1.2.3
  sails-hook-multitenant 0.5.17

I try to do something like this ->

![image](https://user-images.githubusercontent.com/3167082/59927008-19b33880-946e-11e9-8844-4a607d505070.png)

and got this -> 

![image](https://user-images.githubusercontent.com/3167082/59927124-52eba880-946e-11e9-96c9-a8d579287189.png)

the other methods work fine!

**Comment by acalvoa** [comment]
Oh, it's great bug. I will fix and comment the resolution to this bug.
Thx for report this problem in the hook.

**Comment by cyupa** [comment]
@acalvoa thanks for sharing this on GitHub. I'm new to Sails so I don't yet know my way around it but I was wondering about how this goes about multi tenancy, how does it separate data/access to data? By table schema, connection, row access level?

**Comment by acalvoa** [comment]
@cyupa The multitenancy database connection, use differents databases (database connections) to access data by each client in your platform, normally in the same DBMS.
The main idea, is separate the data between clients, obtaining two benefits. 
- The access to data is totally separate, conserving the data schema and structures avoiding merge of data across clients.
- Allow query with better performance, because the clients queries only read in tables with his data, avoiding read, select and find in tables with a large volume of not relevant data.

**Comment by cyupa** [comment]
Thanks for taking time to provide me with this answer. 
Much appreciated.

**Comment by acalvoa** [comment]
Hello guys, sorry for the delay coding a solution for this issue.
The solution was published in the PR #12. with package versión 0.5.19
Any question or bug finded, please tell me for fix them in short.
Thx for your contributions.
@xhb if the solution its Ok?, can u close the issue. Thx a lot
